config/routes.rb
ResumeAssistant::Application.routes.draw do
  resources :activity_entries
  resources :work_entries
  resources :users
  resources :education_entries
  resources :resumes
  resources :entries
  
  
  match "/education_entries/:id/show_formatted" => 'education_entries#show_formatted', via: 'get', :as => :education_entry_show_formatted 
  
  root 'users#index'
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :resume
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
    @education_entries = EducationEntry.all
    @work_entries = WorkEntry.all
    @activity_entries = ActivityEntry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:resume_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resume_id %><br>
    <%= f.text_field :resume_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>List of all Entries</h1>

<h2>Education Entries:</h2>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Graduation date</th>
      <th>Degree</th>
      <th>Major</th>
      <th>Gpa</th>
      <th>Accolades</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @education_entries.each do |education_entry| %>
      <tr>
        <td><%= education_entry.school %></td>
        <td><%= education_entry.graduation_date %></td>
        <td><%= education_entry.degree %></td>
        <td><%= education_entry.major %></td>
        <td><%= education_entry.gpa %></td>
        <td><%= education_entry.accolades %></td>
        <td><%= link_to 'Show', education_entry %></td>
        <td><%= link_to 'Edit', edit_education_entry_path(education_entry) %></td>
        <td><%= link_to 'Destroy', education_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Work Entries:</h2>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @work_entries.each do |work_entry| %>
      <tr>
        <td><%= work_entry.Position %></td>
        <td><%= work_entry.Company %></td>
        <td><%= work_entry.start_date %></td>
        <td><%= work_entry.end_date %></td>
        <td><%= work_entry.description %></td>
        <td><%= link_to 'Show', work_entry %></td>
        <td><%= link_to 'Edit', edit_work_entry_path(work_entry) %></td>
        <td><%= link_to 'Destroy', work_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Work Entries:</h2>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Organization</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th>Resume</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_entries.each do |activity_entry| %>
      <tr>
        <td><%= activity_entry.position %></td>
        <td><%= activity_entry.organization %></td>
        <td><%= activity_entry.start_date %></td>
        <td><%= activity_entry.end_date %></td>
        <td><%= activity_entry.description %></td>
        <td><%= activity_entry.resume.resume_name %></td>
        <td><%= link_to 'Show', activity_entry %></td>
        <td><%= link_to 'Edit', edit_activity_entry_path(activity_entry) %></td>
        <td><%= link_to 'Destroy', activity_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Create a New Entry of Type:</h2>
<%= link_to 'Education', new_education_entry_path %> |
<%= link_to 'Work', new_work_entry_path %> |
<%= link_to 'Activity', new_activity_entry_path %> 

app/views/entries/new.html.erb
<h1>New entry</h1>

<!-- <%= render 'form' %>
-->
<h2>Entry Type:</h2>
<div><%= link_to 'Education', new_education_entry_path %> </div>
<div><%= link_to 'Work', new_work_entry_path %> </div>
<div><%= link_to 'Activity', new_activity_entry_path %> </div>

<br><br>

<%= link_to 'Entries Index', entries_path %>
<%= link_to 'Resume Index', resumes_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resume:</strong>
  <%= @entry.resume %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>