config/routes.rb
ResumeAssistant::Application.routes.draw do
  resources :activity_entries
  resources :work_entries
  resources :users
  resources :education_entries
  resources :resumes
  resources :entries
  
  
  match "/education_entries/:id/show_formatted" => 'education_entries#show_formatted', via: 'get', :as => :education_entry_show_formatted 
  
  root 'users#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :resumes
  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  #has_many :resumes

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #Get Resume this entry belongs to
    @Resumes = Resume.all
    @UsersResumes = Array.new
    @EducationEntries = Array.new
    @ActivityEntries = Array.new
    @WorkEntries = Array.new
    
    @Resumes.each do |resume|
      if resume.user_id == @user.id
       @UsersResumes.push(resume)
      
      
      #Get Education Entries
      @Educations = EducationEntry.all
      @Educations.each do |education|
        if education.resume_id == resume.id
    
          @EducationEntries.push(education)
        end
      end 
  
      #Get Work Entries
      @Works = WorkEntry.all
      @Works.each do |work|
        if work.resume_id == resume.id
    
          @WorkEntries.push(work)
        end
      end 
  
      #Get Work Entries
      @Activities = ActivityEntry.all
      @Activities.each do |activity|
        if activity.resume_id == resume.id
          @ActivityEntries.push(activity)
        end
      end 
    end # if resume.user_id = @user.id
    end #end loop
    
    
  end
  
  #Desired Functionality
  # GET /users/1/resumes
  # def resumes
#     #Get Resume this entry belongs to
#     @Resumes = Resume.all
#     @UsersResumes = Array.new
#     @Resumes.each do |resume|
#       if resume.user_id == @user.id
#     
#        @UsersResumes.push(resume)
#       end
#     end 
#   end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/resumes.html.erb
<h1>Your Resumes</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>User</th>
	  <th>Date Created</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	  
    <% @UsersResumes.each do |resume| %>
      <tr>
        <td><%= resume.user_name %></td>
        <td><%= resume.email %></td>
        <td><%= resume.phone %></td>
        <td><%= resume.address %></td>
        <td><%= resume.user %></td>
		<td><%= resume.date_created %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3> User Info </h3>
  <strong>Name:</strong>
  <%= @user.name %>
  <strong>Email:</strong>
  <%= @user.email %>

<br>
<br>

<h1> Your Resumes </h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>User</th>
	  <th>Date Created</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	  
    <% @UsersResumes.each do |resume| %>
      <tr>
        <td><%= resume.user_name %></td>
        <td><%= resume.email %></td>
        <td><%= resume.phone %></td>
        <td><%= resume.address %></td>
        <td><%= resume.user.name %></td>
		<td><%= resume.date_created %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create a New Resume', new_resume_path %>

<h2>Education Entries:</h2>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Graduation date</th>
      <th>Degree</th>
      <th>Major</th>
      <th>Gpa</th>
      <th>Accolades</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @EducationEntries.each do |education_entry| %>
      <tr>
        <td><%= education_entry.school %></td>
        <td><%= education_entry.graduation_date %></td>
        <td><%= education_entry.degree %></td>
        <td><%= education_entry.major %></td>
        <td><%= education_entry.gpa %></td>
        <td><%= education_entry.accolades %></td>
        <td><%= link_to 'Show', education_entry %></td>
        <td><%= link_to 'Edit', edit_education_entry_path(education_entry) %></td>
        <td><%= link_to 'Destroy', education_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td> <%= link_to 'Show Formatted Entry', education_entry_show_formatted_path(education_entry)%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Education Entry', new_education_entry_path %>

<br>

<h2>Work Entries:</h2>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @WorkEntries.each do |work_entry| %>
      <tr>
        <td><%= work_entry.Position %></td>
        <td><%= work_entry.Company %></td>
        <td><%= work_entry.start_date %></td>
        <td><%= work_entry.end_date %></td>
        <td><%= work_entry.description %></td>
        <td><%= link_to 'Show', work_entry %></td>
        <td><%= link_to 'Edit', edit_work_entry_path(work_entry) %></td>
        <td><%= link_to 'Destroy', work_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Work Entry', new_work_entry_path %>

<br>

<h2>Activity Entries:</h2>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Organization</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th>Resume</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ActivityEntries.each do |activity_entry| %>
      <tr>
        <td><%= activity_entry.position %></td>
        <td><%= activity_entry.organization %></td>
        <td><%= activity_entry.start_date %></td>
        <td><%= activity_entry.end_date %></td>
        <td><%= activity_entry.description %></td>
        <td><%= activity_entry.resume.resume_name %></td>
        <td><%= link_to 'Show', activity_entry %></td>
        <td><%= link_to 'Edit', edit_activity_entry_path(activity_entry) %></td>
        <td><%= link_to 'Destroy', activity_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Activity Entry', new_activity_entry_path %> 

<br>

<%= link_to 'Edit User Info', edit_user_path(@user) %> 

<br>

<%= link_to 'User Index', users_path %> - This only exists, because we have not implemented authentication

   
   