config/routes.rb
ResumeAssistant::Application.routes.draw do
  resources :activity_entries
  resources :work_entries
  resources :users
  resources :education_entries
  resources :resumes
  resources :entries
  
  
  match "/education_entries/:id/show_formatted" => 'education_entries#show_formatted', via: 'get', :as => :education_entry_show_formatted 
  
  root 'users#index'
  

end

app/models/work_entry.rb
class WorkEntry < ActiveRecord::Base
  belongs_to :resume
  validates :Position, presence: true
  validates :Company, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :resume, presence: true
  
end

app/controllers/work_entries_controller.rb
class WorkEntriesController < ApplicationController
  before_action :set_work_entry, only: [:show, :edit, :update, :destroy]

  # GET /work_entries
  # GET /work_entries.json
  def index
    @work_entries = WorkEntry.all
  end

  # GET /work_entries/1
  # GET /work_entries/1.json
  def show
    #Get Resume and user this entry belongs to
      @tempResume = Resume.find_by id: @work_entry.resume_id
      @currentResume = @tempResume.id
      @user = User.find_by id: @tempResume.user_id

  end

  # GET /work_entries/new
  def new
    @work_entry = WorkEntry.new
  end

  # GET /work_entries/1/edit
  def edit
    #Get Resume and user this entry belongs to
    @tempResume = Resume.find_by id: @work_entry.resume_id
    @currentResume = @tempResume.id
    @user = User.find_by id: @tempResume.user_id
  end

  # POST /work_entries
  # POST /work_entries.json
  def create
    @work_entry = WorkEntry.new(work_entry_params)

    respond_to do |format|
      if @work_entry.save
        format.html { redirect_to @work_entry, notice: 'Work entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @work_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @work_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_entries/1
  # PATCH/PUT /work_entries/1.json
  def update
    respond_to do |format|
      if @work_entry.update(work_entry_params)
        format.html { redirect_to @work_entry, notice: 'Work entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_entries/1
  # DELETE /work_entries/1.json
  def destroy
    @work_entry.destroy
    respond_to do |format|
      format.html { redirect_to work_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_entry
      @work_entry = WorkEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_entry_params
      params.require(:work_entry).permit(:Position, :Company, :start_date, :end_date, :description, :resume_id,)
    end
end

app/helpers/work_entries_helper.rb
module WorkEntriesHelper
end

app/views/work_entries/_form.html.erb
<%= form_for(@work_entry) do |f| %>
  <% if @work_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_entry.errors.count, "error") %> prohibited this work_entry from being saved:</h2>

      <ul>
      <% @work_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Position %><br>
    <%= f.text_field :Position %>
  </div>
  <div class="field">
    <%= f.label :Company %><br>
    <%= f.text_field :Company %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  
  <div class="field">
    <%= f.label :resume %><br>
	<%= f.collection_select :resume_id, Resume.all, :id, :resume_name, :prompt =>
	true %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_entries/edit.html.erb
<h1>Editing work_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_entry %> |
<%= link_to 'Show Resume', resume_path(@currentResume) %> |
<%= link_to 'User Page', user_path(@user) %>>

app/views/work_entries/index.html.erb
<h1>Listing work_entries</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @work_entries.each do |work_entry| %>
      <tr>
        <td><%= work_entry.Position %></td>
        <td><%= work_entry.Company %></td>
        <td><%= work_entry.start_date %></td>
        <td><%= work_entry.end_date %></td>
        <td><%= work_entry.description %></td>
        <td><%= link_to 'Show', work_entry %></td>
        <td><%= link_to 'Edit', edit_work_entry_path(work_entry) %></td>
        <td><%= link_to 'Destroy', work_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work entry', new_work_entry_path %>

app/views/work_entries/new.html.erb
<h1>New Work Entry</h1>

<%= render 'form' %>

app/views/work_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <strong> Resume: </strong>
 <%= @work_entry.resume.try(:resume_name) %> <br>
 <%= @work_entry.resume.try(:resume_id) %>
</p>

<p>
  <strong>Position:</strong>
  <%= @work_entry.Position %>
</p>

<p>
  <strong>Company:</strong>
  <%= @work_entry.Company %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @work_entry.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @work_entry.end_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_entry.description %>
</p>

<%= link_to 'Edit', edit_work_entry_path(@work_entry) %> |
<%= link_to 'New Entry', new_entry_path %> 
<!-- ><% if @work_entry.try(:resume) %> -->
| <%= link_to 'Show Resume', resume_path(@currentResume) %> |
<%= link_to 'User Page', user_path(@user) %>
<!--<% end %> -->