config/routes.rb
ResumeAssistant::Application.routes.draw do
  resources :activity_entries
  resources :work_entries
  resources :users
  resources :education_entries
  resources :resumes
  resources :entries
  
  
  match "/education_entries/:id/show_formatted" => 'education_entries#show_formatted', via: 'get', :as => :education_entry_show_formatted 
  
  root 'users#index'
  

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
  has_many :educational_entries
  before_save { self.email = email.downcase }
  validates :resume_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  validates :user, presence: true
                    
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  # entries 
  # for EducationEntry.All do |entry| 
  #    if entry.resume_id == @resume.resume_id
  #      entries.add(entry)
  #    end  
  #  end  
  
  #Get Education Entries
  @Educations = EducationEntry.all
  @EducationPosts = Array.new
  @Educations.each do |education|
    if education.resume_id == @resume.id
    
      @EducationPosts.push(education)
    end
  end 
  
  #Get Work Entries
  @Works = WorkEntry.all
  @WorkPosts = Array.new
  @Works.each do |work|
    if work.resume_id == @resume.id
    
      @WorkPosts.push(work)
    end
  end 
  
  #Get Work Entries
  @Activities = ActivityEntry.all
  @ActivityPosts = Array.new
  @Activities.each do |activity|
    if activity.resume_id == @resume.id
    
      @ActivityPosts.push(activity)
    end
  end 
  
  @user = User.find_by id: @resume.user_id
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
    @user = User.find_by id: @resume.user_id
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resume }
      else
        format.html { render action: 'new' }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:user_name, :resume_name, :date_created, :email, :phone, :address, :user_id)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
	
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= @resume.date_created = Date.current() %>

  <div class="field">
    <%= f.label :resume_name %><br>
    <%= f.text_field :resume_name %>
  </div>
  <div class="field">
    <%= f.label :user_name %> (as you would like it to appear on the resume)<br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  
  <div class="field">
    <%= f.label :user %><br>
 	<%= f.collection_select :user_id, User.all, :id, :name, :prompt =>
  true %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'User Page', user_path(@user) %>

app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>User</th>
	  <th>Date Created</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	  
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.user_name %></td>
        <td><%= resume.email %></td>
        <td><%= resume.phone %></td>
        <td><%= resume.address %></td>
        <td><%= resume.user %></td>
		<td><%= resume.date_created %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>
<%= link_to 'New Entry', new_entry_path %>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<%= @resume.date_created = Date.current() %>
<p id="notice"><%= notice %></p>

<p>
 <strong> User: </strong>
 <%= @resume.user.try(:name) %> <br>
 <%= @resume.user.try(:user_id) %>
 <%= link_to 'Go to Your User Page', user_path(@user) %>
</p>

<h3>General Information</h3>
<div>
  <strong>Resume Name:</strong>
  <%= @resume.resume_name %>
</div>

<div>
  <strong>Date Created:</strong>
  <%= @resume.date_created %>
</div>

<div>
  <strong>Name:</strong>
  <%= @resume.user_name %>
</div>

<div>
  <strong>Email:</strong>
  <%= @resume.email %>
</div>

<div>
  <strong>Phone:</strong>
  <%= @resume.phone %>
</div>

<div>
  <strong>Address:</strong>
  <%= @resume.address %>
</div>
<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', user_path(@user) %>

<h3>-- Education --</h3>
<p> 
  <% @EducationPosts.each do |post| %>
  <div>
   <strong> School: </strong>
   <%= post.school %>
  </div>
  
  <div>
   <strong> Graduation Date: </strong>
   <%= post.graduation_date %>
  </div>
	
  <div>
   <strong> Degree: </strong>
   <%= post.degree %>
  </div>
  
  <div>
   <strong> Major: </strong>
   <%= post.major %>
  </div>
  
  <div>
   <strong> GPA: </strong>
   <%= post.gpa %>
  </div>
  
  <div>
   <strong> Accolades: </strong>
   <%= post.accolades %>
  </div>
  	
	<br>
	
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_education_entry_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	
	<br>
  <% end %>
</p>

<%= link_to 'New Education Entry', new_education_entry_path %>

<h3>-- Work Experience --</h3>
<p> 
  <% @WorkPosts.each do |post| %>
  <div>
	<div>
   <strong> Position: </strong>
   <%= post.Position %>
	</div>
   
   <div>
    <strong> Company: </strong>
    <%= post.Company %>
   </div>
  
   <div>
    <strong> Start Date: </strong>
    <%= post.start_date %>
   </div>
	
   <div>
    <strong> End Date: </strong>
    <%= post.end_date %>
   </div>
  
   <div>
    <strong> Description: </strong>
    <%= post.description %>
   </div>
  </div>
  
  <td><%= link_to 'Show', post %></td>
  <td><%= link_to 'Edit', edit_work_entry_path(post) %></td>
  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  
  <br>
   <% end %>
</p>

<%= link_to 'New Work Entry', new_work_entry_path %>

<h3>-- Activity Experience --</h3>
<p> 
  <% @ActivityPosts.each do |post| %>
  <div>
	<div>
   	   	<strong> Position: </strong>
   	 	<%= post.position %>
	</div>
   
    <div>
     <strong> Organization: </strong>
     <%= post.organization %>
    </div>
  
    <div>
     <strong> Start Date: </strong>
     <%= post.start_date %>
    </div>
	
    <div>
     <strong> End Date: </strong>
     <%= post.end_date %>
    </div>
  
    <div>
     <strong> Description: </strong>
     <%= post.description %>
  </div>
  
  <td><%= link_to 'Show', post %></td>
  <td><%= link_to 'Edit', edit_activity_entry_path(post) %></td>
  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  
  <br>
   <% end %>
  </p> 
   <%= link_to 'New Activity Entry', new_activity_entry_path %> 
   